MODEL:
  img_size: 32
  patch_size: 1
  in_channels: 3
  embed_dim: 16
  num_classes: 5
  depths: [2, 2, 2, 2]
  num_heads: [1, 4, 4, 8]
  window_size: 4
  ape: False  # absolute position embedding
  patch_norm: True  # apply layer normaliztion after embedding
  mlp_ratio: 4.0
  pyramid_Fusion: True # set it on False for FC model
  qkv_bias: True
  attn_drop_rate: 0
  drop_path_rate: 0.2
  drop_rate: 0
  drop_path_rate: 0.1 
  

TRAIN:
  epochs: 100
  lr: 0.00001
  batch_size: 32

DATA:
  train_scene: 'Ottawa'
  test_scene: 'Quebec'
  train_percentage: 80




